import { buildAuthorizationHeader } from "./auth";
import type { GoogleVoiceEnv } from "./env";
import { parseThreadListResponse } from "./parse";
import type { Thread } from "./types";

const API_ROOT = "https://clients6.google.com/voice/v1/voiceclient";
const PAGE_ORIGIN = "https://voice.google.com";
const REQUEST_ORIGIN = "https://clients6.google.com";

/**
 * Minimal client for Google Voice's internal (undocumented) web API,
 * authenticated by replaying a browser session's cookies rather than OAuth.
 *
 * @precondition Constructed with credentials from an active, authenticated
 *   voice.google.com session (see {@link loadEnv} / .env.example).
 */
export class GoogleVoiceClient {
  constructor(private readonly env: GoogleVoiceEnv) {}

  private headers(extraContentLength?: number): Record<string, string> {
    const headers: Record<string, string> = {
      "Content-Type": "application/json+protobuf",
      Cookie: this.env.cookie,
      Authorization: buildAuthorizationHeader(this.env.sapisid, PAGE_ORIGIN),
      "X-Goog-AuthUser": this.env.authUser,
      "X-Client-Version": this.env.clientVersion,
      "X-Origin": PAGE_ORIGIN,
      "X-Referer": PAGE_ORIGIN,
      "X-Requested-With": "XMLHttpRequest",
      "X-Goog-Encode-Response-If-Executable": "base64",
      Origin: REQUEST_ORIGIN,
    };
    if (extraContentLength !== undefined) {
      headers["Content-Length"] = String(extraContentLength);
    }
    return headers;
  }

  private url(path: string): string {
    return `${API_ROOT}/${path}?alt=protojson&key=${this.env.apiKey}`;
  }

  /**
   * Fetches every thread (conversation) and its events for the signed-in
   * account, including each event's plaintext message body.
   *
   * @precondition Client was constructed with valid, unexpired credentials.
   * @postcondition Resolves to every thread visible to the account; throws
   *   if the HTTP request fails or the response isn't valid JSON.
   */
  async listThreads(): Promise<Thread[]> {
    // [threadType=2 (SMS), pageSize=100, unknown=50] — matches a real
    // captured request body; the server rejects an empty "[]" body with 400.
    const body = "[2,100,50]";
    const res = await fetch(this.url("api2thread/list"), {
      method: "POST",
      headers: this.headers(new TextEncoder().encode(body).length),
      body,
    });
    if (!res.ok) {
      throw new Error(`api2thread/list failed: ${res.status} ${res.statusText}`);
    }
    const responseBody = await res.json();
    return parseThreadListResponse(responseBody);
  }

  /**
   * Sends an SMS to a thread. `text` is the plain message body — Google
   * Voice's send request carries it verbatim (index 4 of the request
   * array), the same way `api2thread/list` echoes it back verbatim in each
   * event row (see {@link parseThreadEvent}).
   *
   * The real web client also attaches two anti-abuse tokens to this
   * request: a WAA/BotGuard attestation token (generated via
   * `waa-pa.clients6.google.com/$rpc/google.internal.waa.v1.Waa/Create`
   * followed by running the obfuscated JS challenge it returns — the same
   * mechanism YouTube uses for its "poToken") and what appears to be a
   * reCAPTCHA-style token. Neither is generated by this client; both must
   * be supplied by the caller (e.g. replayed from a fresh capture, or
   * produced by a real browser session). Omitting `tokens` sends without
   * them, which a live capture confirmed the server rejects with 401.
   *
   * @precondition `threadId` matches an existing thread (e.g.
   *   `"t.+15551234567"`); `tmpId` is a client-chosen unique numeric string
   *   used to correlate this send with its eventual event row.
   * @postcondition Resolves to the raw parsed JSON response on success;
   *   throws on a non-2xx HTTP response.
   */
  async sendMessage(
    threadId: string,
    text: string,
    tmpId: string,
    tokens?: { attestationToken: string; recaptchaToken: string },
  ): Promise<unknown> {
    const body = JSON.stringify([
      null,
      null,
      null,
      null,
      text,
      threadId,
      null,
      null,
      [Number(tmpId)],
      null,
      tokens == null
        ? null
        : [tokens.attestationToken, null, null, tokens.recaptchaToken],
    ]);
    const res = await fetch(this.url("api2thread/sendsms"), {
      method: "POST",
      headers: this.headers(new TextEncoder().encode(body).length),
      body,
    });
    if (!res.ok) {
      throw new Error(`api2thread/sendsms failed: ${res.status} ${res.statusText}`);
    }
    return res.json();
  }
}
